title: Sean McClellan # your name (or website title) here
logo: "/images/headshot.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">
  <a href="https://seanm4.github.io/resume/Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/sean-mcclellan-998841141/">LinkedIn</a> |
  <a href="https://github.com/seanm4">GitHub</a>
  </p>
 
  Graduate Student at the University of Pennsylvania earning a Master's of Urban Spatial Analytics Degree - Graduating May 2022
  <br><br>
  Graduated Cum Laude from Drexel Univeristy in 2021 with a Bachelor's Degree in Criminology concentrated on Justice Informatics.
  <br><br>
  <a href="https://www.seanmcclellan.myportfolio.com/">Photography Website</a> 
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: G-B2529CPNBE # your Google Analytics tracking ID here
