title: Sean McClellan # your name (or website title) here
logo: "/images/headshot.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Graduate student at the University of Pennsylvania
  <br><br>
  Master's of Urban Spatial Analytics - Graduating May 2022
  <br><br>
  <br><br>
  <a href="https://www.seanmcclellan.myportfolio.com/">View my Website</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-B2529CPNBE # your Google Analytics tracking ID here
