title: Sean McClellan # your name (or website title) here
logo: "/images/headshot.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Graduate Student at the University of Pennsylvania
  <br><br>
  Master's of Urban Spatial Analytics - Graduating May 2022
  <br><br>
  Graduated Cum Laude from Drexel Univeristy in 2021 with a Bachelor's Degree in Criminology concentrated on Justice Informatics.
  <br><br>
  <a href="https://www.seanmcclellan.myportfolio.com/">Photography Website</a> 
  <br><br>
  <a href="https://docs.google.com/viewer?url=https://raw.githubusercontent.com/seanm4/resume/main/Resume.pdf">View my Resume</a>
  
theme: jekyll-theme-minimal
google_analytics: G-B2529CPNBE # your Google Analytics tracking ID here
